### ISSUE TITLE
Support for svd2rust v0.12.x

### ISSUE THREAD

**Issue by Yarikx** [pftbest/msp430g2553#3]
Is support of a new way of interacting with peripherals (using new svd2rust) planned?

**Comment by pftbest** [comment]
Yes, of course. I was working on this during impl days, and I already have patches for svd2rust, but I'm still updating msp430-rt. I should finish in one or two days.

**Comment by Yarikx** [comment]
Cool! That's great.
Thanks for a quick response.

**Comment by pftbest** [comment]
I still working on this, it took me longer than I thought, sorry.

**Comment by cr1901** [comment]
@Yarikx @pftbest This can be closed as soon as `v0.2.0` is published, assuming `svd2rust v0.17.0` is a superset of `v0.12.x`. Do you object if I publish it now (`msp430` and `msp430-rt` have already been published)?

Please update the `CHANGELOG` if you get to publishing before I do!

**Comment by pftbest** [comment]
Published v0.2.0, thanks!
